insert into cliente (nome) values ('Mercado do João');
insert into cliente (nome) values ('Fale Mais');
insert into cliente (nome) values ('Maria de Souza da Silva');
insert into cliente (nome) values ('Gomes Inovação');
insert into cliente (nome) values ('Diginess Software');
insert into cliente (nome) values ('Bravospan Indústria de Alimentos');
insert into cliente (nome) values ('Digiverse Seguros');
insert into cliente (nome) values ('Jatz Logística');
insert into cliente (nome) values ('Megamix Internet');
insert into cliente (nome) values ('Tetrape Lotéricas');
insert into cliente (nome) values ('Panishare Panificadora');
insert into cliente (nome) values ('Dynacero Sites e Hospedagem');
insert into cliente (nome) values ('Atlafire Livraria');
insert into cliente (nome) values ('Brasilbug Cosméticos');
insert into cliente (nome) values ('ClinicXS Cabeleireiros');
insert into cliente (nome) values ('Voomia Telefonia');
insert into cliente (nome) values ('Truzzy Modas e Acessórios');
insert into cliente (nome) values ('Novabox Games e Informática');
insert into cliente (nome) values ('Lumil Móveis para Escritório');
insert into cliente (nome) values ('Renx Perfumaria');
insert into cliente (nome) values ('Zaex Serviços Web');
insert into cliente (nome) values ('Moncom Agência de Eventos');
insert into cliente (nome) values ('Vifera Comércio de Plantas');
insert into cliente (nome) values ('Detemp Serviços');
insert into cliente (nome) values ('Plustie Petshop');
insert into cliente (nome) values ('Tegrow Comércio Atacadista');
insert into cliente (nome) values ('Jaway Espetos e Bebidas');
insert into cliente (nome) values ('Zecom Consultoria em Redes');